### ISSUE TITLE
panic when extending string lifetime

### ISSUE THREAD

**Issue by seppo0010** [tcr/rust-webplatform#17]
I have this two versions of a simple page that should do the same thing. However the first one (using `let` to keep the value) is panicking while the second is not. I tried adding a `.clone()` and it did not fix the problem.

```rust
extern crate webplatform;

fn main() {
    let document = webplatform::init();
    let body = document.element_query("body").unwrap();
    body.html_set("
        <select>
            <option></option>
            <option value=\"Cargo.toml\">Cargo.toml</option>
            <option value=\"src/main.rs\">src/main.rs</option>
        </select>
    ");

    let select = document.element_query("select").unwrap();
    select.on("change", |event| {
            let f = event.target.unwrap().prop_get_str("value");
            webplatform::alert(&*f);
    });
}
```

```rust
extern crate webplatform;

fn main() {
    let document = webplatform::init();
    let body = document.element_query("body").unwrap();
    body.html_set("
        <select>
            <option></option>
            <option value=\"Cargo.toml\">Cargo.toml</option>
            <option value=\"src/main.rs\">src/main.rs</option>
        </select>
    ");

    let select = document.element_query("select").unwrap();
    select.on("change", |event| {
            webplatform::alert(&*event.target.unwrap().prop_get_str("value"));
    });
}
```

Stacktrace:
```
Uncaught abort("Assertion failed: the runtime was exited (use NO_EXIT_RUNTIME to keep it alive after main() exits)") at Error
    at jsStackTrace (http://localhost:8000/target/asmjs-unknown-emscripten/debug/example-05-fileeditor.js:1092:13)
    at stackTrace (http://localhost:8000/target/asmjs-unknown-emscripten/debug/example-05-fileeditor.js:1109:12)
    at abort (http://localhost:8000/target/asmjs-unknown-emscripten/debug/example-05-fileeditor.js:35270:44)
    at assert (http://localhost:8000/target/asmjs-unknown-emscripten/debug/example-05-fileeditor.js:399:5)
    at asm._malloc (http://localhost:8000/target/asmjs-unknown-emscripten/debug/example-05-fileeditor.js:34954:1)
    at ___cxa_allocate_exception (http://localhost:8000/target/asmjs-unknown-emscripten/debug/example-05-fileeditor.js:1842:14)
    at ___rust_start_panic (http://localhost:8000/target/asmjs-unknown-emscripten/debug/example-05-fileeditor.js:23844:8)
    at _rust_panic (http://localhost:8000/target/asmjs-unknown-emscripten/debug/example-05-fileeditor.js:13558:8)
    at __ZN3std9panicking20rust_panic_with_hook17h9c5ff0e4f1740e9eE (http://localhost:8000/target/asmjs-unknown-emscripten/debug/example-05-fileeditor.js:12779:9)
    at Array.__ZN3std9panicking11begin_panic17hab4851815c22504eE (http://localhost:8000/target/asmjs-unknown-emscripten/debug/example-05-fileeditor.js:12630:3)
```

**Comment by seppo0010** [comment]
My bad, I had to call `webplatform::spin();`
